DROP TABLE IF EXISTS Book;

CREATE TABLE IF NOT EXISTS Book(
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(64),
    RELEASE_YEAR LONG
);

INSERT INTO Book(TITLE, RELEASE_YEAR) VALUES ('Harry Potter - Voldemort Strikes Back', 2010);
INSERT INTO Book(TITLE, RELEASE_YEAR) VALUES ('Star Wars - Goblet of Juice', 2005);
INSERT INTO Book(TITLE, RELEASE_YEAR) VALUES ('Harry Potter - A New Hope', 2019);
INSERT INTO Book(TITLE, RELEASE_YEAR) VALUES ('Star Wars - Prisoner of the Death Star', 1980);
